const PEXELS_IMAGES = {
  Electronics: [
    'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1038916/pexels-photo-1038916.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=600',
  ],
  Clothing: [
    'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/2220316/pexels-photo-2220316.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?auto=compress&cs=tinysrgb&w=600',
  ],
  Books: [
    'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/694740/pexels-photo-694740.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1130980/pexels-photo-1130980.jpeg?auto=compress&cs=tinysrgb&w=600',
  ],
  Accessories: [
    'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1191531/pexels-photo-1191531.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1927259/pexels-photo-1927259.jpeg?auto=compress&cs=tinysrgb&w=600',
  ],
  Home: [
    'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/2079249/pexels-photo-2079249.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1358900/pexels-photo-1358900.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/3705944/pexels-photo-3705944.jpeg?auto=compress&cs=tinysrgb&w=600',
  ],
  Sports: [
    'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/863988/pexels-photo-863988.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/2729899/pexels-photo-2729899.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg?auto=compress&cs=tinysrgb&w=600',
    'https://images.pexels.com/photos/1618269/pexels-photo-1618269.jpeg?auto=compress&cs=tinysrgb&w=600',
  ],
};

export const CATEGORIES = [
  {
    id: 'electronics',
    name: 'Electronics',
    description: 'Gadgets, devices & tech',
    image: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: '💻',
    count: 5,
  },
  {
    id: 'clothing',
    name: 'Clothing',
    description: 'Fashion for every style',
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: '👕',
    count: 5,
  },
  {
    id: 'books',
    name: 'Books',
    description: 'Knowledge & entertainment',
    image: 'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: '📚',
    count: 5,
  },
  {
    id: 'accessories',
    name: 'Accessories',
    description: 'Complete your look',
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: '⌚',
    count: 5,
  },
  {
    id: 'home',
    name: 'Home',
    description: 'Decor & essentials',
    image: 'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: '🏠',
    count: 5,
  },
  {
    id: 'sports',
    name: 'Sports',
    description: 'Gear up & get moving',
    image: 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=600',
    icon: '⚽',
    count: 5,
  },
];

export const MOCK_PRODUCTS = [
  // Electronics (5)
  {
    id: 1, name: 'Pro Wireless Headphones', category: 'Electronics', categoryId: 'electronics',
    price: 149.99, originalPrice: 199.99,
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life, Hi-Res audio, and ultra-comfortable over-ear design. Perfect for commuting, working, or just enjoying your music.',
    shortDescription: 'Noise-cancelling wireless headphones with 30hr battery',
    image: PEXELS_IMAGES.Electronics[0],
    images: [PEXELS_IMAGES.Electronics[0], PEXELS_IMAGES.Electronics[1], PEXELS_IMAGES.Electronics[2]],
    stock: 24, inStock: true, rating: 4.8, reviews: 312, featured: true,
  },
  {
    id: 2, name: 'Smart Watch Series X', category: 'Electronics', categoryId: 'electronics',
    price: 299.99, originalPrice: 349.99,
    description: 'Advanced smartwatch featuring health monitoring, GPS, always-on display, and up to 7 days battery life. Compatible with iOS and Android.',
    shortDescription: 'Advanced smartwatch with health monitoring & GPS',
    image: PEXELS_IMAGES.Electronics[1],
    images: [PEXELS_IMAGES.Electronics[1], PEXELS_IMAGES.Electronics[0], PEXELS_IMAGES.Electronics[3]],
    stock: 18, inStock: true, rating: 4.7, reviews: 245, featured: true,
  },
  {
    id: 3, name: '4K Ultra HD Monitor', category: 'Electronics', categoryId: 'electronics',
    price: 449.99, originalPrice: 549.99,
    description: '27-inch 4K IPS display with 99% sRGB color gamut, HDR support, and ultra-thin bezels. Ideal for creative professionals and gamers.',
    shortDescription: '27-inch 4K IPS monitor with HDR & thin bezels',
    image: PEXELS_IMAGES.Electronics[2],
    images: [PEXELS_IMAGES.Electronics[2], PEXELS_IMAGES.Electronics[4], PEXELS_IMAGES.Electronics[1]],
    stock: 0, inStock: false, rating: 4.9, reviews: 178, featured: false,
  },
  {
    id: 4, name: 'Mechanical Keyboard RGB', category: 'Electronics', categoryId: 'electronics',
    price: 89.99, originalPrice: 119.99,
    description: 'Tenkeyless mechanical keyboard with Cherry MX switches, customizable RGB backlight, and durable aluminum frame. Built for typists and gamers alike.',
    shortDescription: 'TKL mechanical keyboard with RGB and aluminum frame',
    image: PEXELS_IMAGES.Electronics[3],
    images: [PEXELS_IMAGES.Electronics[3], PEXELS_IMAGES.Electronics[0], PEXELS_IMAGES.Electronics[2]],
    stock: 42, inStock: true, rating: 4.6, reviews: 521, featured: false,
  },
  {
    id: 5, name: 'Portable Bluetooth Speaker', category: 'Electronics', categoryId: 'electronics',
    price: 59.99, originalPrice: 79.99,
    description: 'Compact waterproof speaker with 360-degree sound, 20-hour playtime, and built-in microphone. Your perfect outdoor companion.',
    shortDescription: 'Waterproof portable speaker with 20hr battery',
    image: PEXELS_IMAGES.Electronics[4],
    images: [PEXELS_IMAGES.Electronics[4], PEXELS_IMAGES.Electronics[1], PEXELS_IMAGES.Electronics[3]],
    stock: 67, inStock: true, rating: 4.5, reviews: 893, featured: true,
  },

  // Clothing (5)
  {
    id: 6, name: 'Essential Cotton Tee', category: 'Clothing', categoryId: 'clothing',
    price: 24.99, originalPrice: 34.99,
    description: 'Premium 100% organic cotton t-shirt with a relaxed fit and ribbed crew neck. Available in multiple colors. Sustainably made.',
    shortDescription: 'Premium organic cotton t-shirt, relaxed fit',
    image: PEXELS_IMAGES.Clothing[0],
    images: [PEXELS_IMAGES.Clothing[0], PEXELS_IMAGES.Clothing[2], PEXELS_IMAGES.Clothing[4]],
    stock: 150, inStock: true, rating: 4.4, reviews: 1204, featured: false,
  },
  {
    id: 7, name: 'Slim Fit Chinos', category: 'Clothing', categoryId: 'clothing',
    price: 69.99, originalPrice: 89.99,
    description: 'Versatile slim-fit chino trousers made from stretch twill fabric. Comfortable for all-day wear, smart enough for the office.',
    shortDescription: 'Stretch slim-fit chinos for all-day comfort',
    image: PEXELS_IMAGES.Clothing[1],
    images: [PEXELS_IMAGES.Clothing[1], PEXELS_IMAGES.Clothing[0], PEXELS_IMAGES.Clothing[3]],
    stock: 85, inStock: true, rating: 4.3, reviews: 672, featured: false,
  },
  {
    id: 8, name: 'Oversized Hoodie', category: 'Clothing', categoryId: 'clothing',
    price: 54.99, originalPrice: 74.99,
    description: 'Cozy oversized hoodie made from heavyweight French terry fleece. Features a kangaroo pocket and adjustable drawstring hood.',
    shortDescription: 'Heavyweight French terry oversized hoodie',
    image: PEXELS_IMAGES.Clothing[2],
    images: [PEXELS_IMAGES.Clothing[2], PEXELS_IMAGES.Clothing[1], PEXELS_IMAGES.Clothing[4]],
    stock: 0, inStock: false, rating: 4.7, reviews: 2341, featured: true,
  },
  {
    id: 9, name: 'Linen Summer Dress', category: 'Clothing', categoryId: 'clothing',
    price: 79.99, originalPrice: 99.99,
    description: 'Elegant linen blend midi dress with a flowing silhouette. Perfect for warm days and special occasions. Machine washable.',
    shortDescription: 'Flowing linen midi dress for warm weather',
    image: PEXELS_IMAGES.Clothing[3],
    images: [PEXELS_IMAGES.Clothing[3], PEXELS_IMAGES.Clothing[0], PEXELS_IMAGES.Clothing[2]],
    stock: 32, inStock: true, rating: 4.6, reviews: 445, featured: true,
  },
  {
    id: 10, name: 'Leather Bomber Jacket', category: 'Clothing', categoryId: 'clothing',
    price: 189.99, originalPrice: 249.99,
    description: 'Classic leather bomber jacket with ribbed cuffs and hem, full-zip closure, and two front pockets. A timeless wardrobe staple.',
    shortDescription: 'Classic leather bomber with ribbed trim',
    image: PEXELS_IMAGES.Clothing[4],
    images: [PEXELS_IMAGES.Clothing[4], PEXELS_IMAGES.Clothing[1], PEXELS_IMAGES.Clothing[3]],
    stock: 12, inStock: true, rating: 4.8, reviews: 289, featured: false,
  },

  // Books (5)
  {
    id: 11, name: 'Atomic Habits', category: 'Books', categoryId: 'books',
    price: 16.99, originalPrice: 24.99,
    description: 'An easy and proven way to build good habits and break bad ones. James Clear delivers a step-by-step guide to making good habits inevitable and bad habits impossible.',
    shortDescription: 'Build good habits and break bad ones — James Clear',
    image: PEXELS_IMAGES.Books[0],
    images: [PEXELS_IMAGES.Books[0], PEXELS_IMAGES.Books[2], PEXELS_IMAGES.Books[4]],
    stock: 200, inStock: true, rating: 4.9, reviews: 45321, featured: true,
  },
  {
    id: 12, name: 'The Psychology of Money', category: 'Books', categoryId: 'books',
    price: 14.99, originalPrice: 21.99,
    description: 'Morgan Housel shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life\'s most important topics.',
    shortDescription: 'Timeless lessons on wealth, greed, and happiness',
    image: PEXELS_IMAGES.Books[1],
    images: [PEXELS_IMAGES.Books[1], PEXELS_IMAGES.Books[0], PEXELS_IMAGES.Books[3]],
    stock: 180, inStock: true, rating: 4.8, reviews: 23456, featured: false,
  },
  {
    id: 13, name: 'Deep Work', category: 'Books', categoryId: 'books',
    price: 15.99, originalPrice: 22.99,
    description: 'Rules for focused success in a distracted world by Cal Newport. Learn how to develop a deep work habit and transform your professional life.',
    shortDescription: 'Rules for focused success in a distracted world',
    image: PEXELS_IMAGES.Books[2],
    images: [PEXELS_IMAGES.Books[2], PEXELS_IMAGES.Books[1], PEXELS_IMAGES.Books[4]],
    stock: 0, inStock: false, rating: 4.7, reviews: 18920, featured: false,
  },
  {
    id: 14, name: 'Sapiens: A Brief History', category: 'Books', categoryId: 'books',
    price: 17.99, originalPrice: 25.99,
    description: 'A groundbreaking narrative of humanity\'s creation and evolution by Yuval Noah Harari. Explores how Homo sapiens came to dominate the planet.',
    shortDescription: 'A groundbreaking history of humankind — Harari',
    image: PEXELS_IMAGES.Books[3],
    images: [PEXELS_IMAGES.Books[3], PEXELS_IMAGES.Books[0], PEXELS_IMAGES.Books[2]],
    stock: 95, inStock: true, rating: 4.9, reviews: 67823, featured: true,
  },
  {
    id: 15, name: 'The Lean Startup', category: 'Books', categoryId: 'books',
    price: 13.99, originalPrice: 19.99,
    description: 'How Today\'s Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses by Eric Ries. Essential reading for founders.',
    shortDescription: 'Essential guide for modern entrepreneurs — Ries',
    image: PEXELS_IMAGES.Books[4],
    images: [PEXELS_IMAGES.Books[4], PEXELS_IMAGES.Books[1], PEXELS_IMAGES.Books[3]],
    stock: 120, inStock: true, rating: 4.6, reviews: 34521, featured: false,
  },

  // Accessories (5)
  {
    id: 16, name: 'Minimalist Leather Wallet', category: 'Accessories', categoryId: 'accessories',
    price: 39.99, originalPrice: 59.99,
    description: 'Slim RFID-blocking leather wallet with 6 card slots and a cash pocket. Fits perfectly in your front or back pocket.',
    shortDescription: 'Slim RFID-blocking leather wallet, 6 card slots',
    image: PEXELS_IMAGES.Accessories[0],
    images: [PEXELS_IMAGES.Accessories[0], PEXELS_IMAGES.Accessories[2], PEXELS_IMAGES.Accessories[4]],
    stock: 78, inStock: true, rating: 4.5, reviews: 1562, featured: false,
  },
  {
    id: 17, name: 'Classic Aviator Sunglasses', category: 'Accessories', categoryId: 'accessories',
    price: 49.99, originalPrice: 69.99,
    description: 'Timeless aviator sunglasses with polarized UV400 lenses and lightweight metal frame. Available in gold, silver, and gunmetal.',
    shortDescription: 'Polarized UV400 aviator sunglasses, metal frame',
    image: PEXELS_IMAGES.Accessories[1],
    images: [PEXELS_IMAGES.Accessories[1], PEXELS_IMAGES.Accessories[0], PEXELS_IMAGES.Accessories[3]],
    stock: 56, inStock: true, rating: 4.6, reviews: 934, featured: true,
  },
  {
    id: 18, name: 'Canvas Tote Bag', category: 'Accessories', categoryId: 'accessories',
    price: 29.99, originalPrice: 39.99,
    description: 'Durable heavyweight canvas tote with reinforced handles and interior zip pocket. Fits a 15" laptop. Eco-friendly and stylish.',
    shortDescription: 'Heavy canvas tote with laptop pocket',
    image: PEXELS_IMAGES.Accessories[2],
    images: [PEXELS_IMAGES.Accessories[2], PEXELS_IMAGES.Accessories[1], PEXELS_IMAGES.Accessories[4]],
    stock: 0, inStock: false, rating: 4.4, reviews: 2100, featured: false,
  },
  {
    id: 19, name: 'Leather Belt', category: 'Accessories', categoryId: 'accessories',
    price: 34.99, originalPrice: 49.99,
    description: 'Full-grain leather dress belt with a brushed metal buckle. Classic and versatile, suitable for both casual and formal wear.',
    shortDescription: 'Full-grain leather belt with metal buckle',
    image: PEXELS_IMAGES.Accessories[3],
    images: [PEXELS_IMAGES.Accessories[3], PEXELS_IMAGES.Accessories[0], PEXELS_IMAGES.Accessories[2]],
    stock: 45, inStock: true, rating: 4.3, reviews: 789, featured: false,
  },
  {
    id: 20, name: 'Wool Beanie Hat', category: 'Accessories', categoryId: 'accessories',
    price: 22.99, originalPrice: 32.99,
    description: 'Warm and stylish merino wool beanie with a ribbed design. Available in 8 classic colors. One size fits most.',
    shortDescription: 'Merino wool ribbed beanie, 8 color options',
    image: PEXELS_IMAGES.Accessories[4],
    images: [PEXELS_IMAGES.Accessories[4], PEXELS_IMAGES.Accessories[1], PEXELS_IMAGES.Accessories[3]],
    stock: 110, inStock: true, rating: 4.7, reviews: 1876, featured: false,
  },

  // Home (5)
  {
    id: 21, name: 'Ceramic Coffee Mug Set', category: 'Home', categoryId: 'home',
    price: 34.99, originalPrice: 49.99,
    description: 'Set of 4 handcrafted ceramic mugs in complementary earth tones. Dishwasher and microwave safe. Holds 12oz each.',
    shortDescription: 'Set of 4 handcrafted ceramic mugs, 12oz each',
    image: PEXELS_IMAGES.Home[0],
    images: [PEXELS_IMAGES.Home[0], PEXELS_IMAGES.Home[2], PEXELS_IMAGES.Home[4]],
    stock: 65, inStock: true, rating: 4.8, reviews: 3421, featured: true,
  },
  {
    id: 22, name: 'Linen Throw Pillow', category: 'Home', categoryId: 'home',
    price: 27.99, originalPrice: 39.99,
    description: 'Soft linen decorative throw pillow with hidden zipper. Removable cover, machine washable. Adds texture and warmth to any room.',
    shortDescription: 'Soft linen throw pillow with removable cover',
    image: PEXELS_IMAGES.Home[1],
    images: [PEXELS_IMAGES.Home[1], PEXELS_IMAGES.Home[0], PEXELS_IMAGES.Home[3]],
    stock: 88, inStock: true, rating: 4.5, reviews: 1243, featured: false,
  },
  {
    id: 23, name: 'Bamboo Cutting Board', category: 'Home', categoryId: 'home',
    price: 32.99, originalPrice: 44.99,
    description: 'Large eco-friendly bamboo cutting board with juice groove and non-slip feet. Naturally antimicrobial and gentle on knife edges.',
    shortDescription: 'Large eco bamboo cutting board with juice groove',
    image: PEXELS_IMAGES.Home[2],
    images: [PEXELS_IMAGES.Home[2], PEXELS_IMAGES.Home[1], PEXELS_IMAGES.Home[4]],
    stock: 0, inStock: false, rating: 4.6, reviews: 2109, featured: false,
  },
  {
    id: 24, name: 'Scented Soy Candle', category: 'Home', categoryId: 'home',
    price: 24.99, originalPrice: 34.99,
    description: 'Hand-poured soy wax candle with cotton wick. Fragrance options: lavender, cedar, vanilla, and eucalyptus. Burns for 50+ hours.',
    shortDescription: 'Hand-poured soy candle, 50hr burn time',
    image: PEXELS_IMAGES.Home[3],
    images: [PEXELS_IMAGES.Home[3], PEXELS_IMAGES.Home[0], PEXELS_IMAGES.Home[2]],
    stock: 145, inStock: true, rating: 4.9, reviews: 5678, featured: true,
  },
  {
    id: 25, name: 'Minimalist Wall Clock', category: 'Home', categoryId: 'home',
    price: 44.99, originalPrice: 64.99,
    description: 'Silent movement wall clock with a clean minimalist face and wooden frame. Battery powered. Available in 10-inch and 12-inch.',
    shortDescription: 'Silent minimalist wall clock, wooden frame',
    image: PEXELS_IMAGES.Home[4],
    images: [PEXELS_IMAGES.Home[4], PEXELS_IMAGES.Home[1], PEXELS_IMAGES.Home[3]],
    stock: 37, inStock: true, rating: 4.4, reviews: 876, featured: false,
  },

  // Sports (5)
  {
    id: 26, name: 'Yoga Mat Premium', category: 'Sports', categoryId: 'sports',
    price: 59.99, originalPrice: 79.99,
    description: 'Extra thick 6mm non-slip yoga mat with alignment lines and carrying strap. Made from eco-friendly natural rubber. 72" x 24".',
    shortDescription: 'Extra thick non-slip yoga mat with alignment lines',
    image: PEXELS_IMAGES.Sports[0],
    images: [PEXELS_IMAGES.Sports[0], PEXELS_IMAGES.Sports[2], PEXELS_IMAGES.Sports[4]],
    stock: 53, inStock: true, rating: 4.7, reviews: 7823, featured: true,
  },
  {
    id: 27, name: 'Resistance Band Set', category: 'Sports', categoryId: 'sports',
    price: 29.99, originalPrice: 44.99,
    description: 'Set of 5 resistance bands with varying resistance levels (10–50 lbs). Includes carry bag and exercise guide. Great for home workouts.',
    shortDescription: '5-piece resistance band set with carry bag',
    image: PEXELS_IMAGES.Sports[1],
    images: [PEXELS_IMAGES.Sports[1], PEXELS_IMAGES.Sports[0], PEXELS_IMAGES.Sports[3]],
    stock: 124, inStock: true, rating: 4.5, reviews: 4512, featured: false,
  },
  {
    id: 28, name: 'Running Hydration Belt', category: 'Sports', categoryId: 'sports',
    price: 34.99, originalPrice: 49.99,
    description: 'Lightweight adjustable running belt with 2 BPA-free water bottles and zippered storage pocket. One size fits all.',
    shortDescription: 'Adjustable running belt with 2 water bottles',
    image: PEXELS_IMAGES.Sports[2],
    images: [PEXELS_IMAGES.Sports[2], PEXELS_IMAGES.Sports[1], PEXELS_IMAGES.Sports[4]],
    stock: 0, inStock: false, rating: 4.3, reviews: 2341, featured: false,
  },
  {
    id: 29, name: 'Foam Roller Deep Tissue', category: 'Sports', categoryId: 'sports',
    price: 24.99, originalPrice: 34.99,
    description: 'High-density foam roller for muscle recovery, myofascial release, and deep tissue massage. 13 inches, supports up to 500 lbs.',
    shortDescription: 'High-density foam roller for muscle recovery',
    image: PEXELS_IMAGES.Sports[3],
    images: [PEXELS_IMAGES.Sports[3], PEXELS_IMAGES.Sports[0], PEXELS_IMAGES.Sports[2]],
    stock: 89, inStock: true, rating: 4.6, reviews: 9871, featured: false,
  },
  {
    id: 30, name: 'Adjustable Dumbbell Set', category: 'Sports', categoryId: 'sports',
    price: 199.99, originalPrice: 279.99,
    description: 'Space-saving adjustable dumbbell set ranging from 5 to 52.5 lbs per dumbbell. Quick-change mechanism, replaces 15 sets of dumbbells.',
    shortDescription: 'Quick-adjust dumbbells 5–52.5 lbs, saves space',
    image: PEXELS_IMAGES.Sports[4],
    images: [PEXELS_IMAGES.Sports[4], PEXELS_IMAGES.Sports[1], PEXELS_IMAGES.Sports[3]],
    stock: 8, inStock: true, rating: 4.9, reviews: 1534, featured: true,
  },
];

export const MOCK_ORDERS = [
  {
    id: 'ORD-2024-001', date: '2024-11-15', total: 199.97, status: 'Delivered',
    items: [
      { productId: 1, name: 'Pro Wireless Headphones', quantity: 1, price: 149.99, image: PEXELS_IMAGES.Electronics[0] },
      { productId: 11, name: 'Atomic Habits', quantity: 2, price: 16.99, image: PEXELS_IMAGES.Books[0] },
    ],
    shippingCost: 9.99, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-002', date: '2024-11-20', total: 89.99, status: 'Shipped',
    items: [
      { productId: 4, name: 'Mechanical Keyboard RGB', quantity: 1, price: 89.99, image: PEXELS_IMAGES.Electronics[3] },
    ],
    shippingCost: 0, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-003', date: '2024-11-28', total: 154.97, status: 'Processing',
    items: [
      { productId: 26, name: 'Yoga Mat Premium', quantity: 1, price: 59.99, image: PEXELS_IMAGES.Sports[0] },
      { productId: 6, name: 'Essential Cotton Tee', quantity: 2, price: 24.99, image: PEXELS_IMAGES.Clothing[0] },
      { productId: 24, name: 'Scented Soy Candle', quantity: 1, price: 24.99, image: PEXELS_IMAGES.Home[3] },
    ],
    shippingCost: 5.99, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-004', date: '2024-12-01', total: 299.99, status: 'Confirmed',
    items: [
      { productId: 2, name: 'Smart Watch Series X', quantity: 1, price: 299.99, image: PEXELS_IMAGES.Electronics[1] },
    ],
    shippingCost: 0, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-005', date: '2024-12-05', total: 74.97, status: 'Pending',
    items: [
      { productId: 17, name: 'Classic Aviator Sunglasses', quantity: 1, price: 49.99, image: PEXELS_IMAGES.Accessories[1] },
      { productId: 20, name: 'Wool Beanie Hat', quantity: 1, price: 22.99, image: PEXELS_IMAGES.Accessories[4] },
    ],
    shippingCost: 5.99, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-006', date: '2024-10-10', total: 54.99, status: 'Cancelled',
    items: [
      { productId: 8, name: 'Oversized Hoodie', quantity: 1, price: 54.99, image: PEXELS_IMAGES.Clothing[2] },
    ],
    shippingCost: 5.99, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-007', date: '2024-10-22', total: 124.97, status: 'Delivered',
    items: [
      { productId: 21, name: 'Ceramic Coffee Mug Set', quantity: 1, price: 34.99, image: PEXELS_IMAGES.Home[0] },
      { productId: 30, name: 'Adjustable Dumbbell Set', quantity: 1, price: 199.99, image: PEXELS_IMAGES.Sports[4] },
    ],
    shippingCost: 9.99, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-008', date: '2024-09-15', total: 79.99, status: 'Delivered',
    items: [
      { productId: 9, name: 'Linen Summer Dress', quantity: 1, price: 79.99, image: PEXELS_IMAGES.Clothing[3] },
    ],
    shippingCost: 0, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-009', date: '2024-09-28', total: 44.97, status: 'Delivered',
    items: [
      { productId: 12, name: 'The Psychology of Money', quantity: 1, price: 14.99, image: PEXELS_IMAGES.Books[1] },
      { productId: 15, name: 'The Lean Startup', quantity: 2, price: 13.99, image: PEXELS_IMAGES.Books[4] },
    ],
    shippingCost: 5.99, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-010', date: '2024-08-20', total: 249.98, status: 'Delivered',
    items: [
      { productId: 5, name: 'Portable Bluetooth Speaker', quantity: 1, price: 59.99, image: PEXELS_IMAGES.Electronics[4] },
      { productId: 10, name: 'Leather Bomber Jacket', quantity: 1, price: 189.99, image: PEXELS_IMAGES.Clothing[4] },
    ],
    shippingCost: 9.99, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-011', date: '2024-08-05', total: 59.98, status: 'Delivered',
    items: [
      { productId: 27, name: 'Resistance Band Set', quantity: 1, price: 29.99, image: PEXELS_IMAGES.Sports[1] },
      { productId: 29, name: 'Foam Roller Deep Tissue', quantity: 1, price: 24.99, image: PEXELS_IMAGES.Sports[3] },
    ],
    shippingCost: 5.99, address: '123 Main St, New York, NY 10001',
  },
  {
    id: 'ORD-2024-012', date: '2024-07-14', total: 189.99, status: 'Delivered',
    items: [
      { productId: 10, name: 'Leather Bomber Jacket', quantity: 1, price: 189.99, image: PEXELS_IMAGES.Clothing[4] },
    ],
    shippingCost: 0, address: '123 Main St, New York, NY 10001',
  },
];

export default MOCK_PRODUCTS;
